apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin
  namespace: database
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - pgadmin.lab.local
    secretName: pg-tls
  rules:
  - host: pgadmin.lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin-pgadmin4
            port:
              number: 80
