apiVersion: v1
kind: Service
metadata:
  name: amigospremia-api
  namespace: apps
  labels:
    app.kubernetes.io/name: amigospremia-api
    app.kubernetes.io/part-of: amigospremia
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: amigospremia-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
