apiVersion: v1
kind: Secret
metadata:
  name: amigospremia-secrets
  namespace: apps
type: Opaque
stringData:
  APP_NAME: "amigospremiaservice"
  VITE_APP_NAME: "amigospremia"
  DB_HOST: "postgres-postgresql.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "amigospremia"
  REDIS_HOST: "redis-master.database.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "redispassword"