apiVersion: v1
kind: Service
metadata:
  name: amigospremia-web
  namespace: apps
  labels:
    app.kubernetes.io/name: amigospremia-web
    app.kubernetes.io/part-of: amigospremia
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: amigospremia-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
