apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amigospremia
  namespace: apps
  labels:
    app.kubernetes.io/name: amigospremia
    app.kubernetes.io/part-of: amigospremia
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - amigospremia.lab.local
      secretName: amigospremia-tls
  rules:
    - host: amigospremia.lab.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: amigospremia-api
                port:
                  number: 8080

          - path: /
            pathType: Prefix
            backend:
              service:
                name: amigospremia-web
                port:
                  number: 80
