apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-ingress-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EdnaldoLourenco/homelab.git
    targetRevision: main
    path: infra/ingress
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
