apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-cert-manager-config
  namespace: argocd
  argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/EdnaldoLourenco/homelab.git
    targetRevision: main
    path: infra/cert-manager/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
